# -*- coding: utf-8 -*-
"""d360

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1weVjb9amXkV7WE4tCaT15iw3DshpqxnA
"""

from flask import Flask,request
import pandas as pd
dataset = pd.read_excel('d360_dataset.xlsx')

app = Flask(__name__)

@app.route('/webhook',methods=['get','post'])
def webhook():
    req = request.get_json(silent=True,force=True)
    fulfillmentText= ''
    query_result=req.get('queryResult')
    if query_result.get('action') == 'get.address':
        fulfillmentText="Hi"
    return{
        "fulfillmentText" : fulfillmentText,
        "source" : "webhookdata"
    }
if __name__ == 'main':
    app.run()

"""# New Section

# New Section
"""